analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - line_length
  - identifier_name
  - large_tuple
  - trailing_comma
  - cyclomatic_complexity
  - function_body_length
  - todo
  - function_parameter_count
  - nesting
